# main param, -1 means no range limit
resolution: 0.2
probHit: 0.7
probMiss: 0.4
thresMin: 0.12
thresMax: 0.97
OccupancyThres: 0.5

# whether prune tree
prune_tree: false

# ===> Ground Segmentation, so that we will not count ground
filterGroundPlane: true
m_groundFilterDistance: 0.1
m_groundFilterAngle: 0.2
m_groundFilterPlaneDistance: 0.2

# ===> Filter
filterNoise: true
filterMeanK: 50
StddevMulThresh: 1.0

# will label dynamic as intensity 1 not removed.
replace_intensity: false

verbose: false

# no need to tune, if your data range is small
maxRange: -1.0
minRange: -1.0